runtime: nodejs20
service: api

# Standard environment with F1 instance class
instance_class: F1

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 0
  min_pending_latency: automatic
  max_pending_latency: automatic
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

# Environment variables for Doppler
env_variables:
  PORT: "8080"
  DOPPLER_TOKEN: ${DOPPLER_SERVICE_TOKEN}
  DOPPLER_PROJECT: ${DOPPLER_PROJECT_NAME}
  DOPPLER_CONFIG: ${ENVIRONMENT}_nest

# Entrypoint - runs the start script with Doppler
entrypoint: >
  ./bin/doppler run
  --token="$DOPPLER_TOKEN"
  --project="$DOPPLER_PROJECT"
  --config="$DOPPLER_CONFIG"
  -- sh -c 'echo "🚀 Starting application..."; exec node dist/main'
  
# Handlers for static files (if needed)
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
