export enum Configkey {
    ENVIRONMENT = 'ENVIRONMENT',
    APP_NAME = 'APP_NAME',
    APP_SECRET = 'APP_SECRET',
    AUTH0_DOMAIN = 'AUTH0_DOMAIN',
    AUTH0_MANAGEMENT_CLIENT_ID = 'AUTH0_MANAGEMENT_CLIENT_ID',
    AUTH0_MANAGEMENT_CLIENT_SECRET = 'AUTH0_MANAGEMENT_CLIENT_SECRET',
    AUTH0_RESOURCE_API_AUDIENCE = 'AUTH0_RESOURCE_API_AUDIENCE',
    MONGODB_URL = 'MONGODB_URL',
    POSTGRES_URL = 'POSTGRES_URL',
    REDIS_URL = 'REDIS_URL',

    CORS_ALLOWED_ORIGIN = 'CORS_ALLOWED_ORIGIN',
    CORS_ALLOWED_METHODS = 'CORS_ALLOWED_METHODS',

    GOOGLE_RECAPTCHA_SITE_KEY = 'GOOGLE_RECAPTCHA_SITE_KEY',
    GOOGLE_RECAPTCHA_SECURITY_KEY = 'GOOGLE_RECAPTCHA_SECURITY_KEY',

    GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
    GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
    GOOGLE_REDIRECT_URI = 'GOOGLE_REDIRECT_URI',

    FIREBASE_FILESTORAGE_BUCKET = 'FIREBASE_FILESTORAGE_BUCKET',
    FIREBASE_CREDENTIAL = 'FIREBASE_CREDENTIAL',

    ENABLE_EMAIL_MOCKING = 'ENABLE_EMAIL_MOCKING',
    MOCKED_EMAIL_ADDRESS = 'MOCKED_EMAIL_ADDRESS',
    ENABLE_PROD_MODE = 'ENABLE_PROD_MODE',

    APP_BE_URL = 'APP_BE_URL',
    APP_FE_URL = 'APP_FE_URL',
    APP_PUBLIC_URL = 'APP_PUBLIC_URL',
    EMAIL_SENDER = "EMAIL_SENDER",
    NODE_ENV = "NODE_ENV",
    LOG_LEVEL = "LOG_LEVEL",
    SLACK_WEBHOOK_URL = "SLACK_WEBHOOK_URL",

    PROP_DONATION_AMOUNT = "PROP_DONATION_AMOUNT",
}