export enum Configkey {
    ENVIRONMENT = 'ENVIRONMENT',
    APP_NAME = 'APP_NAME',
    APP_SECRET = 'APP_SECRET',
    AUTH0_BASE_URL = 'AUTH0_BASE_URL',
    AUTH0_MANAGEMENT_CLIENT_ID = 'AUTH0_MANAGEMENT_CLIENT_ID',
    AUTH0_MANAGEMENT_CLIENT_SECRET = 'AUTH0_MANAGEMENT_CLIENT_SECRET',
    AUTH0_RESOURCE_API_AUDIENCE = 'AUTH0_RESOURCE_API_AUDIENCE',
    AUTH0_MANAGEMENT_API_AUDIENCE = 'AUTH0_MANAGEMENT_API_AUDIENCE',
    AUTH0_ISSUER_URI = 'AUTH0_ISSUER_URI',
    MONGODB_URL = 'MONGODB_URL',
    POSTGRES_URL = 'POSTGRES_URL',
    REDIS_URL = 'REDIS_URL',

    CORS_ALLOWED_ORIGIN = 'CORS_ALLOWED_ORIGIN',
    CORS_ALLOWED_METHODS = 'CORS_ALLOWED_METHODS',

    GOOGLE_RECAPTCHA_SITE_KEY = 'GOOGLE_RECAPTCHA_SITE_KEY',
    GOOGLE_RECAPTCHA_SECURITY_KEY = 'GOOGLE_RECAPTCHA_SECURITY_KEY',

    GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
    GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
    GOOGLE_REDIRECT_URI = 'GOOGLE_REDIRECT_URI',
    GOOGLE_SCOPES = 'GOOGLE_SCOPES',

    FIREBASE_FILESTORAGE_BUCKET = 'FIREBASE_FILESTORAGE_BUCKET',
    FIREBASE_CREDENTIAL = 'FIREBASE_CREDENTIAL',

    ENABLE_EMAIL_MOCKING_FOR_TEST = 'ENABLE_EMAIL_MOCKING_FOR_TEST',
    MOCKED_EMAIL_ADDRESS = 'MOCKED_EMAIL_ADDRESS',
    ENABLE_PROD_MODE = 'ENABLE_PROD_MODE_FOR_TEST',

    APP_LOGIN_URL = 'APP_LOGIN_URL',
}