export enum EmailTemplateName {
    TASK_ASSIGNED = 'TASK_ASSIGNED',
    TASK_UPDATED = 'TASK_UPDATED',
    USER_ONBOARDED = 'USER_ONBOARDED',
    ROLE_ASSIGNED = 'ROLE_ASSIGNED',
    WORKFLOW_UPDATE = "WORKFLOW_UPDATE",
    DONATION_CREATED = "DONATION_CREATED",
    DONATION_PAID = "DONATION_PAID",
    DONATION_REMINDER = "DONATION_REMINDER",
    TASK_REMINDER = "TASK_REMINDER",
}