export enum JobName {
    SEND_ONBOARDING_EMAIL = 'send-onboarding-email',
    UPDATE_USER_ROLE = 'update-user-role',
    START_WORKFLOW_STEP = "START_WORKFLOW_STEP",
    SEND_DONATION_REMINDER_EMAIL = 'send-donation-reminder-email',
    CREATE_DONATION = "CREATE_DONATION",
    SEND_TASK_REMINDER_EMAIL = "SEND_TASK_REMINDER_EMAIL",
    GENERATE_REPORT = "GENERATE_REPORT",
    ENGINE_PROCESS_STEP = "ENGINE_PROCESS_STEP",
    ENGINE_SEND_TASK_REMINDER = "ENGINE_SEND_TASK_REMINDER",
    CREATE_TRANSACTION = "CREATE_TRANSACTION",
}