export enum NotificationKeys {
    DONATION_CREATED = "DONATION_CREATED",
    DONATION_PAID = "DONATION_PAID",
    TASK_ASSIGNED = "TASK_ASSIGNED",
    TASK_STARTED = "TASK_STARTED",
    TASK_REMINDER = "TASK_REMINDER",
    APP_TECHNICAL_ERROR = "APP_TECHNICAL_ERROR",
}