name: Deploy Java App to GCP (Example)

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-gcp-app-engine-v2.yml
    with:
      # Application Configuration
      app_type: 'java'
      tag_name: ${{ github.ref_name }}
      repo_name: ${{ github.event.repository.name }}
      repo_owner_name: ${{ github.repository_owner }}
      environment_name: 'production'
      environment_url: 'https://your-java-app.appspot.com'
      
      # Java-specific Configuration
      java_version: '17'
      maven_command: 'clean package'
      maven_options: '-Dmaven.test.skip=true -Dmaven.javadoc.skip=true'
      target_folder: 'target'
      artifact_pattern: '*.jar'
      
      # GCP Configuration
      gae_app_yaml_path: 'app.yaml'
      gae_service_name: 'default'
      
      # Environment Configuration
      app_env: 'production'
      app_doppler_project_name: 'my-java-app'
      app_log_level: 'INFO'
      
      # Deployment Configuration
      deployment_timeout: 25
      enable_health_check: true
      enable_cache: true
      
      # Cleanup Configuration
      keep_gae_versions: 2
      gcs_keep_days: 7
      
    secrets:
      gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
      gcp_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      app_doppler_service_token: ${{ secrets.DOPPLER_SERVICE_TOKEN }}
      repo_token: ${{ secrets.GITHUB_TOKEN }}
